a=int(input("enter a"))
b=int(input("enter b"))
c=a+b
d=a-b
e=a*b
f=a//b
g=a%b
print(f"{a}+{b}={c}")
print(f"{a}-{b}={d}")
print(f"{a}*{b}={e}")
print(f"{a}//{b}={f}")
print(f"{a}%{b}={g}")
